/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AuthedTransparencyRouteImport } from './routes/_authed/transparency'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSecretaryRouteImport } from './routes/_authed/secretary'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedMemberRouteImport } from './routes/_authed/member'
import { Route as AuthedMeetingsRouteImport } from './routes/_authed/meetings'
import { Route as AuthedLoansRouteImport } from './routes/_authed/loans'
import { Route as AuthedInvestmentsRouteImport } from './routes/_authed/investments'
import { Route as AuthedHelpRouteImport } from './routes/_authed/help'
import { Route as AuthedFeedRouteImport } from './routes/_authed/feed'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedContributionsRouteImport } from './routes/_authed/contributions'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AuthedTransparencyRoute = AuthedTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecretaryRoute = AuthedSecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemberRoute = AuthedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeetingsRoute = AuthedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLoansRoute = AuthedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvestmentsRoute = AuthedInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHelpRoute = AuthedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContributionsRoute = AuthedContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthedBillingRoute
  '/contributions': typeof AuthedContributionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/feed': typeof AuthedFeedRoute
  '/help': typeof AuthedHelpRoute
  '/investments': typeof AuthedInvestmentsRoute
  '/loans': typeof AuthedLoansRoute
  '/meetings': typeof AuthedMeetingsRoute
  '/member': typeof AuthedMemberRoute
  '/members': typeof AuthedMembersRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/secretary': typeof AuthedSecretaryRoute
  '/settings': typeof AuthedSettingsRoute
  '/transparency': typeof AuthedTransparencyRoute
  '/app/create': typeof AppCreateRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthedBillingRoute
  '/contributions': typeof AuthedContributionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/feed': typeof AuthedFeedRoute
  '/help': typeof AuthedHelpRoute
  '/investments': typeof AuthedInvestmentsRoute
  '/loans': typeof AuthedLoansRoute
  '/meetings': typeof AuthedMeetingsRoute
  '/member': typeof AuthedMemberRoute
  '/members': typeof AuthedMembersRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/secretary': typeof AuthedSecretaryRoute
  '/settings': typeof AuthedSettingsRoute
  '/transparency': typeof AuthedTransparencyRoute
  '/app/create': typeof AppCreateRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/contributions': typeof AuthedContributionsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/help': typeof AuthedHelpRoute
  '/_authed/investments': typeof AuthedInvestmentsRoute
  '/_authed/loans': typeof AuthedLoansRoute
  '/_authed/meetings': typeof AuthedMeetingsRoute
  '/_authed/member': typeof AuthedMemberRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/secretary': typeof AuthedSecretaryRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/transparency': typeof AuthedTransparencyRoute
  '/app/create': typeof AppCreateRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/start'
    | '/terms'
    | '/billing'
    | '/contributions'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/investments'
    | '/loans'
    | '/meetings'
    | '/member'
    | '/members'
    | '/notifications'
    | '/reports'
    | '/secretary'
    | '/settings'
    | '/transparency'
    | '/app/create'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/start'
    | '/terms'
    | '/billing'
    | '/contributions'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/investments'
    | '/loans'
    | '/meetings'
    | '/member'
    | '/members'
    | '/notifications'
    | '/reports'
    | '/secretary'
    | '/settings'
    | '/transparency'
    | '/app/create'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/app'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/start'
    | '/terms'
    | '/_authed/billing'
    | '/_authed/contributions'
    | '/_authed/dashboard'
    | '/_authed/feed'
    | '/_authed/help'
    | '/_authed/investments'
    | '/_authed/loans'
    | '/_authed/meetings'
    | '/_authed/member'
    | '/_authed/members'
    | '/_authed/notifications'
    | '/_authed/reports'
    | '/_authed/secretary'
    | '/_authed/settings'
    | '/_authed/transparency'
    | '/app/create'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authed/transparency': {
      id: '/_authed/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof AuthedTransparencyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/secretary': {
      id: '/_authed/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof AuthedSecretaryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/member': {
      id: '/_authed/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthedMemberRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meetings': {
      id: '/_authed/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthedMeetingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/loans': {
      id: '/_authed/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthedLoansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/investments': {
      id: '/_authed/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthedInvestmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/help': {
      id: '/_authed/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedHelpRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contributions': {
      id: '/_authed/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthedContributionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedContributionsRoute: typeof AuthedContributionsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedHelpRoute: typeof AuthedHelpRoute
  AuthedInvestmentsRoute: typeof AuthedInvestmentsRoute
  AuthedLoansRoute: typeof AuthedLoansRoute
  AuthedMeetingsRoute: typeof AuthedMeetingsRoute
  AuthedMemberRoute: typeof AuthedMemberRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSecretaryRoute: typeof AuthedSecretaryRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTransparencyRoute: typeof AuthedTransparencyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedContributionsRoute: AuthedContributionsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedHelpRoute: AuthedHelpRoute,
  AuthedInvestmentsRoute: AuthedInvestmentsRoute,
  AuthedLoansRoute: AuthedLoansRoute,
  AuthedMeetingsRoute: AuthedMeetingsRoute,
  AuthedMemberRoute: AuthedMemberRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSecretaryRoute: AuthedSecretaryRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTransparencyRoute: AuthedTransparencyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
