/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as JoinApplyRouteImport } from './routes/join/apply'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminChamasRouteImport } from './routes/admin/chamas'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AuthedTransparencyRouteImport } from './routes/_authed/transparency'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSecretaryRouteImport } from './routes/_authed/secretary'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedMemberRouteImport } from './routes/_authed/member'
import { Route as AuthedMeetingsRouteImport } from './routes/_authed/meetings'
import { Route as AuthedLoansRouteImport } from './routes/_authed/loans'
import { Route as AuthedInvestmentsRouteImport } from './routes/_authed/investments'
import { Route as AuthedHelpRouteImport } from './routes/_authed/help'
import { Route as AuthedFeedRouteImport } from './routes/_authed/feed'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCreateChamaRouteImport } from './routes/_authed/create-chama'
import { Route as AuthedContributionsRouteImport } from './routes/_authed/contributions'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedAdminApplicationsRouteImport } from './routes/_authed/admin.applications'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinApplyRoute = JoinApplyRouteImport.update({
  id: '/join/apply',
  path: '/join/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChamasRoute = AdminChamasRouteImport.update({
  id: '/chamas',
  path: '/chamas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedTransparencyRoute = AuthedTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecretaryRoute = AuthedSecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemberRoute = AuthedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeetingsRoute = AuthedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLoansRoute = AuthedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvestmentsRoute = AuthedInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHelpRoute = AuthedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCreateChamaRoute = AuthedCreateChamaRouteImport.update({
  id: '/create-chama',
  path: '/create-chama',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContributionsRoute = AuthedContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminApplicationsRoute = AuthedAdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthedBillingRoute
  '/contributions': typeof AuthedContributionsRoute
  '/create-chama': typeof AuthedCreateChamaRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/feed': typeof AuthedFeedRoute
  '/help': typeof AuthedHelpRoute
  '/investments': typeof AuthedInvestmentsRoute
  '/loans': typeof AuthedLoansRoute
  '/meetings': typeof AuthedMeetingsRoute
  '/member': typeof AuthedMemberRoute
  '/members': typeof AuthedMembersRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/secretary': typeof AuthedSecretaryRoute
  '/settings': typeof AuthedSettingsRoute
  '/transparency': typeof AuthedTransparencyRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/chamas': typeof AdminChamasRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/apply': typeof JoinApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/join/': typeof JoinIndexRoute
  '/admin/applications': typeof AuthedAdminApplicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthedBillingRoute
  '/contributions': typeof AuthedContributionsRoute
  '/create-chama': typeof AuthedCreateChamaRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/feed': typeof AuthedFeedRoute
  '/help': typeof AuthedHelpRoute
  '/investments': typeof AuthedInvestmentsRoute
  '/loans': typeof AuthedLoansRoute
  '/meetings': typeof AuthedMeetingsRoute
  '/member': typeof AuthedMemberRoute
  '/members': typeof AuthedMembersRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/secretary': typeof AuthedSecretaryRoute
  '/settings': typeof AuthedSettingsRoute
  '/transparency': typeof AuthedTransparencyRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/chamas': typeof AdminChamasRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/apply': typeof JoinApplyRoute
  '/admin': typeof AdminIndexRoute
  '/join': typeof JoinIndexRoute
  '/admin/applications': typeof AuthedAdminApplicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/contributions': typeof AuthedContributionsRoute
  '/_authed/create-chama': typeof AuthedCreateChamaRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/help': typeof AuthedHelpRoute
  '/_authed/investments': typeof AuthedInvestmentsRoute
  '/_authed/loans': typeof AuthedLoansRoute
  '/_authed/meetings': typeof AuthedMeetingsRoute
  '/_authed/member': typeof AuthedMemberRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/secretary': typeof AuthedSecretaryRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/transparency': typeof AuthedTransparencyRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/chamas': typeof AdminChamasRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/apply': typeof JoinApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/join/': typeof JoinIndexRoute
  '/_authed/admin/applications': typeof AuthedAdminApplicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/no-access'
    | '/privacy'
    | '/terms'
    | '/billing'
    | '/contributions'
    | '/create-chama'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/investments'
    | '/loans'
    | '/meetings'
    | '/member'
    | '/members'
    | '/notifications'
    | '/reports'
    | '/secretary'
    | '/settings'
    | '/transparency'
    | '/admin/announcements'
    | '/admin/chamas'
    | '/admin/pricing'
    | '/auth/reset-password'
    | '/join/apply'
    | '/admin/'
    | '/join/'
    | '/admin/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/no-access'
    | '/privacy'
    | '/terms'
    | '/billing'
    | '/contributions'
    | '/create-chama'
    | '/dashboard'
    | '/feed'
    | '/help'
    | '/investments'
    | '/loans'
    | '/meetings'
    | '/member'
    | '/members'
    | '/notifications'
    | '/reports'
    | '/secretary'
    | '/settings'
    | '/transparency'
    | '/admin/announcements'
    | '/admin/chamas'
    | '/admin/pricing'
    | '/auth/reset-password'
    | '/join/apply'
    | '/admin'
    | '/join'
    | '/admin/applications'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/no-access'
    | '/privacy'
    | '/terms'
    | '/_authed/billing'
    | '/_authed/contributions'
    | '/_authed/create-chama'
    | '/_authed/dashboard'
    | '/_authed/feed'
    | '/_authed/help'
    | '/_authed/investments'
    | '/_authed/loans'
    | '/_authed/meetings'
    | '/_authed/member'
    | '/_authed/members'
    | '/_authed/notifications'
    | '/_authed/reports'
    | '/_authed/secretary'
    | '/_authed/settings'
    | '/_authed/transparency'
    | '/admin/announcements'
    | '/admin/chamas'
    | '/admin/pricing'
    | '/auth/reset-password'
    | '/join/apply'
    | '/admin/'
    | '/join/'
    | '/_authed/admin/applications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  JoinApplyRoute: typeof JoinApplyRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/apply': {
      id: '/join/apply'
      path: '/join/apply'
      fullPath: '/join/apply'
      preLoaderRoute: typeof JoinApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chamas': {
      id: '/admin/chamas'
      path: '/chamas'
      fullPath: '/admin/chamas'
      preLoaderRoute: typeof AdminChamasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/transparency': {
      id: '/_authed/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof AuthedTransparencyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/secretary': {
      id: '/_authed/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof AuthedSecretaryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/member': {
      id: '/_authed/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthedMemberRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meetings': {
      id: '/_authed/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthedMeetingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/loans': {
      id: '/_authed/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthedLoansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/investments': {
      id: '/_authed/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthedInvestmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/help': {
      id: '/_authed/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedHelpRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/create-chama': {
      id: '/_authed/create-chama'
      path: '/create-chama'
      fullPath: '/create-chama'
      preLoaderRoute: typeof AuthedCreateChamaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contributions': {
      id: '/_authed/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthedContributionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/applications': {
      id: '/_authed/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthedAdminApplicationsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedContributionsRoute: typeof AuthedContributionsRoute
  AuthedCreateChamaRoute: typeof AuthedCreateChamaRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedHelpRoute: typeof AuthedHelpRoute
  AuthedInvestmentsRoute: typeof AuthedInvestmentsRoute
  AuthedLoansRoute: typeof AuthedLoansRoute
  AuthedMeetingsRoute: typeof AuthedMeetingsRoute
  AuthedMemberRoute: typeof AuthedMemberRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSecretaryRoute: typeof AuthedSecretaryRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTransparencyRoute: typeof AuthedTransparencyRoute
  AuthedAdminApplicationsRoute: typeof AuthedAdminApplicationsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedContributionsRoute: AuthedContributionsRoute,
  AuthedCreateChamaRoute: AuthedCreateChamaRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedHelpRoute: AuthedHelpRoute,
  AuthedInvestmentsRoute: AuthedInvestmentsRoute,
  AuthedLoansRoute: AuthedLoansRoute,
  AuthedMeetingsRoute: AuthedMeetingsRoute,
  AuthedMemberRoute: AuthedMemberRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSecretaryRoute: AuthedSecretaryRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTransparencyRoute: AuthedTransparencyRoute,
  AuthedAdminApplicationsRoute: AuthedAdminApplicationsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminChamasRoute: typeof AdminChamasRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminChamasRoute: AdminChamasRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  JoinApplyRoute: JoinApplyRoute,
  JoinIndexRoute: JoinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
